### ISSUE TITLE
broken

### ISSUE THREAD

**Issue by ralyodio** [EricCrosson/coinmarketcap-cli#13]
```
$ coinmarketcap btc
(node:643902) UnhandledPromiseRejectionWarning: Error: The website requested returned an error!
    at Request._callback (/home/ettinger/.nvm/versions/node/v12.16.3/lib/node_modules/coinmarketcap-cli/node_modules/table-scraper/index.js:15:23)
    at Request.self.callback (/home/ettinger/.nvm/versions/node/v12.16.3/lib/node_modules/coinmarketcap-cli/node_modules/request/request.js:185:22)
    at Request.emit (events.js:310:20)
    at Request.<anonymous> (/home/ettinger/.nvm/versions/node/v12.16.3/lib/node_modules/coinmarketcap-cli/node_modules/request/request.js:1154:10)
    at Request.emit (events.js:310:20)
    at IncomingMessage.<anonymous> (/home/ettinger/.nvm/versions/node/v12.16.3/lib/node_modules/coinmarketcap-cli/node_modules/request/request.js:1076:12)
    at Object.onceWrapper (events.js:416:28)
    at IncomingMessage.emit (events.js:322:22)
    at endReadableNT (_stream_readable.js:1187:12)
    at processTicksAndRejections (internal/process/task_queues.js:84:21)
(node:643902) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:643902) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

**Comment by EricCrosson** [comment]
Yes, this project is not actively maintained. I'll drop it into archive mode

You are more than welcome to fork and continue maintenance. Happy hacking
